export const SITE_CONFIG = {
  name: "Affordable Locksmith Orlando",
  shortName: "Affordable Locksmith",
  tagline: "Fast, Affordable & Trusted Locksmith in Orlando, FL",
  phone: "(407) 555-0199",
  phoneRaw: "4075550199",
  email: "info@affordablelocksmithorlando.com",
  address: {
    street: "7721 Newlan Dr",
    city: "Orlando",
    state: "FL",
    zip: "32818",
    country: "US",
    full: "7721 Newlan Dr, Orlando, FL 32818",
  },
  geo: {
    lat: 28.5677,
    lng: -81.4637,
  },
  hours: {
    weekdays: "24/7 Emergency Service",
    note: "Available around the clock, every day of the year",
  },
  rating: 4.8,
  reviewCount: 56,
  url: "https://affordablelocksmithorlando.com",
  social: {
    google: "https://www.google.com/maps?cid=8420155941837107426",
  },
  googlePlaceId: "0x88e777ebd8187e9f:0x74da67379a9870e2",
  googleCid: "8420155941837107426",
  googleMapsEmbed: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14012!2d-81.4637!3d28.5677!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88e777ebd8187e9f%3A0x74da67379a9870e2!2sAffordable+Locksmith+Orlando!5e0!3m2!1sen!2sus!4v1",
  licenseNumber: "FL-LIC-2024-LOCK",
  founded: "2015",
  serviceRadius: "30 miles",
} as const;

export const SERVICE_AREAS = [
  { name: "Orlando", slug: "orlando", zip: "32801" },
  { name: "Winter Garden", slug: "winter-garden", zip: "34787" },
  { name: "Ocoee", slug: "ocoee", zip: "34761" },
  { name: "Apopka", slug: "apopka", zip: "32703" },
  { name: "Winter Park", slug: "winter-park", zip: "32789" },
  { name: "Kissimmee", slug: "kissimmee", zip: "34741" },
  { name: "Sanford", slug: "sanford", zip: "32771" },
  { name: "Lake Mary", slug: "lake-mary", zip: "32746" },
  { name: "Altamonte Springs", slug: "altamonte-springs", zip: "32701" },
  { name: "Maitland", slug: "maitland", zip: "32751" },
  { name: "Longwood", slug: "longwood", zip: "32750" },
  { name: "Casselberry", slug: "casselberry", zip: "32707" },
] as const;

export const SERVICES = [
  {
    slug: "emergency-locksmith",
    name: "Emergency Locksmith",
    shortName: "Emergency",
    icon: "AlertTriangle",
    description: "24/7 emergency locksmith services. Locked out? We arrive in 20–30 minutes.",
    heroDescription: "Locked out of your home, car, or business? Our emergency locksmiths are available 24 hours a day, 7 days a week, 365 days a year. We guarantee fast arrival — typically 20 to 30 minutes throughout Orlando.",
    price: "Starting at $45",
    responseTime: "20–30 min",
    popular: true,
  },
  {
    slug: "residential-locksmith",
    name: "Residential Locksmith",
    shortName: "Residential",
    icon: "Home",
    description: "Complete home lock services including installation, rekeying, repair, and smart locks.",
    heroDescription: "Protect your home and family with professional residential locksmith services. From deadbolt installation to complete security upgrades, we keep Orlando homes safe.",
    price: "Starting at $55",
    responseTime: "Same day",
    popular: true,
  },
  {
    slug: "commercial-locksmith",
    name: "Commercial Locksmith",
    shortName: "Commercial",
    icon: "Building2",
    description: "Business security solutions including master key systems, access control, and high-security locks.",
    heroDescription: "Protect your business assets with enterprise-grade security. We serve offices, retail stores, warehouses, and multi-unit properties throughout Orlando.",
    price: "Starting at $75",
    responseTime: "Same day",
    popular: false,
  },
  {
    slug: "automotive-locksmith",
    name: "Automotive Locksmith",
    shortName: "Automotive",
    icon: "Car",
    description: "Car lockouts, key programming, transponder keys, and key fob replacement for all vehicle makes.",
    heroDescription: "Locked out of your car? Lost your car keys? Our automotive locksmiths are trained on all makes and models — domestic, foreign, luxury, and commercial vehicles.",
    price: "Starting at $65",
    responseTime: "20–30 min",
    popular: true,
  },
  {
    slug: "car-key-replacement",
    name: "Car Key Replacement",
    shortName: "Car Keys",
    icon: "KeyRound",
    description: "Replacement car keys cut and programmed on-site for all vehicle makes and models.",
    heroDescription: "Lost your car keys? Need a spare? We cut and program replacement car keys on-site — often faster and cheaper than your dealership.",
    price: "Starting at $95",
    responseTime: "Same day",
    popular: false,
  },
  {
    slug: "car-key-programming",
    name: "Car Key Programming",
    shortName: "Key Programming",
    icon: "Cpu",
    description: "Transponder key programming, remote key fob programming, and push-button start key services.",
    heroDescription: "Modern vehicles require precise electronic key programming. Our certified technicians program transponder keys, smart keys, and key fobs for all makes and models.",
    price: "Starting at $85",
    responseTime: "Same day",
    popular: false,
  },
  {
    slug: "lock-rekeying",
    name: "Lock Rekeying",
    shortName: "Rekeying",
    icon: "RefreshCw",
    description: "Rekey your locks without replacing them. The most cost-effective way to secure your property.",
    heroDescription: "Just moved? Lost a key? Rekeying changes your lock's internal pins so old keys no longer work. It's faster and less expensive than full lock replacement.",
    price: "Starting at $25/lock",
    responseTime: "Same day",
    popular: true,
  },
  {
    slug: "lock-repair",
    name: "Lock Repair",
    shortName: "Repair",
    icon: "Wrench",
    description: "Professional repair for broken, jammed, or damaged locks. All lock brands and types.",
    heroDescription: "A broken lock is a security vulnerability. Our technicians diagnose and repair all types of lock problems — from worn-out cylinders to broken deadbolts — restoring full security.",
    price: "Starting at $45",
    responseTime: "Same day",
    popular: false,
  },
  {
    slug: "safe-opening",
    name: "Safe Opening",
    shortName: "Safe Services",
    icon: "Shield",
    description: "Non-destructive safe opening, combination changes, and safe repair for all brands.",
    heroDescription: "Locked out of your safe? Forgotten your combination? Our safe technicians open all types of safes — residential, commercial, floor safes, and fireproof models — using non-destructive techniques when possible.",
    price: "Starting at $150",
    responseTime: "Same day",
    popular: false,
  },
  {
    slug: "lock-installation",
    name: "Lock Installation",
    shortName: "Installation",
    icon: "PlusSquare",
    description: "Professional installation of deadbolts, smart locks, security locks, and commercial hardware.",
    heroDescription: "Upgrade your security with professionally installed locks. We install all major brands including Schlage, Kwikset, Baldwin, and smart lock systems from August, Yale, and Nest.",
    price: "Starting at $55",
    responseTime: "Same day",
    popular: false,
  },
] as const;

export const TRUST_SIGNALS = [
  { label: "Licensed & Insured", icon: "Shield" },
  { label: "4.8★ Google Rating", icon: "Star" },
  { label: "56+ Reviews", icon: "MessageSquare" },
  { label: "20–30 Min Response", icon: "Clock" },
  { label: "Upfront Pricing", icon: "DollarSign" },
  { label: "24/7 Available", icon: "Phone" },
] as const;

export const REVIEWS = [
  {
    id: 1,
    name: "Maria R.",
    rating: 5,
    date: "2 weeks ago",
    text: "I was locked out of my house at 11pm and they arrived in under 25 minutes. The technician was professional, friendly, and had me back inside quickly. Price was very reasonable. Highly recommend!",
    service: "Emergency House Lockout",
    verified: true,
  },
  {
    id: 2,
    name: "James T.",
    rating: 5,
    date: "1 month ago",
    text: "Called them for a car lockout near International Drive. Fast response, professional service. The technician explained everything clearly and had my car open in minutes. Will definitely use again.",
    service: "Car Lockout",
    verified: true,
  },
  {
    id: 3,
    name: "Sandra K.",
    rating: 5,
    date: "3 weeks ago",
    text: "Needed to rekey all locks after a break-in scare. They came same day, rekeyed 4 locks quickly and charged a fair price. Very professional team. Peace of mind restored!",
    service: "Lock Rekeying",
    verified: true,
  },
  {
    id: 4,
    name: "David M.",
    rating: 5,
    date: "2 months ago",
    text: "Best locksmith in Orlando! I needed a new car key programmed and they did it for half the price the dealership quoted. Great work, fast service. 5 stars all the way.",
    service: "Car Key Programming",
    verified: true,
  },
  {
    id: 5,
    name: "Angela B.",
    rating: 5,
    date: "1 month ago",
    text: "Moved into a new home and had all locks rekeyed. Excellent service from start to finish. On time, professional, and affordable. Already recommended to my neighbors.",
    service: "Lock Rekeying",
    verified: true,
  },
  {
    id: 6,
    name: "Carlos V.",
    rating: 4,
    date: "6 weeks ago",
    text: "Good service for my business. Had them install new commercial locks on our office. Professional installation, clean work. Small delay in arrival but they communicated well about it.",
    service: "Commercial Lock Installation",
    verified: true,
  },
] as const;

export const FAQ_GENERAL = [
  {
    q: "How fast can you arrive for a lockout emergency in Orlando?",
    a: "Our average response time in Orlando is 20 to 30 minutes. We have mobile units stationed throughout the Orlando metro area to ensure rapid response 24 hours a day, 7 days a week.",
  },
  {
    q: "How much does a locksmith cost in Orlando?",
    a: "Our locksmith services start at $45 for basic lockouts. Lock rekeying starts at $25 per lock. Car key programming starts at $85. We provide upfront pricing before any work begins — no hidden fees.",
  },
  {
    q: "Are you available on nights, weekends, and holidays?",
    a: "Yes. We operate 24/7/365 including all holidays, nights, and weekends. Emergency locksmith needs don't follow business hours, and neither do we.",
  },
  {
    q: "Do you require proof of ownership before opening a lock?",
    a: "Yes, for security we require proof of ownership or residency (ID, lease agreement, vehicle registration, or title) before performing any lockout service. This protects our customers and the community.",
  },
  {
    q: "Is Affordable Locksmith Orlando licensed and insured?",
    a: "Yes. We are a fully licensed and insured locksmith company operating in Florida. All technicians are background-checked, trained, and certified.",
  },
  {
    q: "Do you serve areas outside of Orlando?",
    a: "Yes. We serve the greater Orlando metro area including Winter Garden, Ocoee, Apopka, Winter Park, Kissimmee, Sanford, Lake Mary, Altamonte Springs, Maitland, Longwood, and Casselberry.",
  },
  {
    q: "Can you make a car key without the original?",
    a: "Yes. Our automotive locksmiths can cut and program replacement car keys even without the original key, using your vehicle's VIN number and proof of ownership.",
  },
  {
    q: "What payment methods do you accept?",
    a: "We accept cash, all major credit cards (Visa, MasterCard, American Express, Discover), and digital payments including Apple Pay and Google Pay.",
  },
] as const;
